= Агенты и асинхронные действия
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:navlinktext: Agents
:prevpagehref: refs
:prevpagetitle: Refs and Transactions
:nextpagehref: atoms
:nextpagetitle: Atoms

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Как и ссылки, агенты предоставляют общий доступ к изменяемому состоянию. <<refs#,Ссылки>> поддерживают _согласованные_, _синхронные_ изменения _множества_ хранилищ. Агенты обеспечивают _независимое_, _асинхронное_ изменение _отдельных_ хранилищ. Агенты привязаны к одному хранилищу в течении всей его жизни и позволяет проводить изменения хранилища (в новое состояние) в виде действий. Действия - это функции (возможно с аргументами), которые асинхронно применяются к состоянию агента и чьё возвращаемое значение становится новым состоянием агента. Так как действия являются функциями, они также могут быть мультиметодами, а следовательно действия потенциально полиморфны. Также, так как множество функций является http://ru.wikipedia.org/wiki/Открытое_множество[открытым], то множество действий, поддерживаемых агентами также открыто, что резко контрастирует с циклами обработки сообщений предоставляемым другими языками программирования.

Агенты Clojure _реактивны_, не автономны - нет никакого императивного цикла сообщений и нет блокировок. Состояние агента само должно быть неизменяемым (предпочтительно экземпляром одной из коллекций Clojure) и состояние агента всегда немедленно становится доступно для чтения любым другим потоком (при помощи функции http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/deref[deref] или макроса <<reader#,считывателя>> +@+) без каких бы то ни было сообщений, то есть отслеживание не требует согласования или координации.

Agent action dispatches take the form +(send agent fn args*)+. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] (and http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off]) always returns immediately. At some point later, in another thread, the following will happen:

. The given +fn+ will be applied to the _state_ of the Agent and the args, if any were supplied.
. The return value of +fn+ will be passed to the validator function, if one has been set on the Agent. See http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-validator![set-validator!] for details.
. If the validator succeeds or if no validator was given, the return value of the given +fn+ will become the new state of the Agent.
. If any watchers were added to the Agent, they will be called. See http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/add-watch[add-watch] for details.
. If during the function execution any other dispatches are made (directly or indirectly), they will be held until _after_ the state of the Agent has been changed.

If any exceptions are thrown by an action function, no nested dispatches will occur, and the exception will be cached in the Agent itself. When an Agent has errors cached, any subsequent interactions will immediately throw an exception, until the agent's errors are cleared. Agent errors can be examined with http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error] and the agent restarted with http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent].

The actions of all Agents get interleaved amongst threads in a thread pool. At any point in time, at most one action for each Agent is being executed. Actions dispatched to an agent from another single agent or thread will occur in the order they were sent, potentially interleaved with actions dispatched to the same agent from other sources. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] should be used for actions that are CPU limited, while http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off] is appropriate for actions that may block on IO.

Agents are integrated with the STM - any dispatches made in a transaction are held until it commits, and are discarded if it is retried or aborted.

As with all of Clojure's concurrency support, no user-code locking is involved.

Note that use of Agents starts a pool of non-daemon background threads that will prevent shutdown of the JVM. Use http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/shutdown-agents[shutdown-agents] to terminate these threads and allow shutdown.

== Example

This example is an implementation of the send-a-message-around-a-ring test. A chain of n agents is created, then a sequence of m actions are dispatched to the head of the chain and relayed through it.
[source,clojure]
----
(defn relay [x i]
  (when (:next x)
    (send (:next x) relay i))
  (when (and (zero? i) (:report-queue x))
    (.put (:report-queue x) i))
  x)

(defn run [m n]
  (let [q (new java.util.concurrent.SynchronousQueue)
        hd (reduce (fn [next _] (agent {:next next}))
                   (agent {:report-queue q}) (range (dec m)))]
    (doseq [i (reverse (range n))]
      (send hd relay i))
    (.take q)))

; 1 million message sends:
(time (run 1000 1000))
->"Elapsed time: 2959.254 msecs"
----

== Related functions

Create an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent[agent]

Examine an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/deref[deref] _(see also the +@+ <<reader#,reader>> macro)_ http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-handler[error-handler] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-mode[error-mode]

Change Agent state: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent]

Block waiting for an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/await[await] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/await-for[await-for]

Ref validators: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-validator![set-validator!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get-validator[get-validator]

Watchers: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/add-watch[add-watch] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/remove-watch[remove-watch]

Agent thread management: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/shutdown-agents[shutdown-agents]

Agent error management: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-error-handler![set-error-handler!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-handler[error-handler] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-error-mode![set-error-mode!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-mode[error-mode]
