= Агенты и асинхронные действия
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:navlinktext: Agents
:prevpagehref: refs
:prevpagetitle: Refs and Transactions
:nextpagehref: atoms
:nextpagetitle: Atoms

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Как и ссылки, агенты предоставляют общий доступ к изменяемому состоянию. <<refs#,Ссылки>> поддерживают _согласованные_, _синхронные_ изменения _множества_ хранилищ. Агенты обеспечивают _независимое_, _асинхронное_ изменение _отдельных_ хранилищ. Агенты привязаны к одному хранилищу в течении всей его жизни и позволяет проводить изменения хранилища (в новое состояние) в виде действий. Действия - это функции (возможно с аргументами), которые асинхронно применяются к состоянию агента и чьё возвращаемое значение становится новым состоянием агента. Так как действия являются функциями, они также могут быть мультиметодами, а следовательно действия потенциально полиморфны. Также, так как множество функций является http://ru.wikipedia.org/wiki/Открытое_множество[открытым], то множество действий, поддерживаемых агентами также открыто, что резко контрастирует с циклами обработки сообщений предоставляемым другими языками программирования.

Агенты Clojure _реактивны_, не автономны - нет никакого императивного цикла сообщений и нет блокировок. Состояние агента само должно быть неизменяемым (предпочтительно экземпляром одной из коллекций Clojure) и состояние агента всегда немедленно становится доступно для чтения любым другим потоком (при помощи функции http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/deref[deref] или макроса <<reader#,считывателя>> +@+) без каких бы то ни было сообщений, то есть отслеживание не требует согласования или координации.

Отправка действий агенту происходит в форме +(send agent fn args*)+. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] (и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off]) всегда немедленно завершаются. В какой-то момент позже, в другом потоке, произойдет следующее:

. Данная функция +fn+ будет применена к _состоянию_ агента и аргументам, если они предоставлены.
. Значение, возвращенное +fn+ будет передано в функцию-валидатор, если она установлена для агента. Более подробно см. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-validator![set-validator!].
. Если валидатор завершится успешно или его не существует, возвращенное значение данной функции +fn+ станет новым состоянием агента.
. Если какие-либо наблюдатели были зарегистрированы для агента, они будут вызваны. Болле подробно см. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/add-watch[add-watch].
. Если во время выполнения функции осуществлятся любые другие вызовы - напрямую или любым другим способом, они будут ждать, пока состояние агента не изменится.

Если действующая функция сгенерирует какое-либо исключение-ошибку, она будет сохранено агентом. Когда у агента имеется сохраненная ошибка, все последующие взаимодействия будут немедленно завершаться с исключением, пока список сохраненных ошибок в агенте не будет очищен. Ошибки агента могут быть просмотрены с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error], агент может быть перезапущен с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent].

Действия всех агентов выполняются вперемешку в пуле потоков. В любой момент времени выполняется не более одного действия для каждого из агентов. Действия, переданные агенту из другого агента или потока будут обрабатываться в том порядке, в котором они были посланы. Эти действия могут быть перемешаны с другими действиями, посланными тому же агенту из других источников. Функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] должна использоваться для действий-вычислений. Функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off] подходит для действий, которые связаны с блокирующими операциями ввода вывода.

Agents are integrated with the STM - any dispatches made in a transaction are held until it commits, and are discarded if it is retried or aborted.

As with all of Clojure's concurrency support, no user-code locking is involved.

Note that use of Agents starts a pool of non-daemon background threads that will prevent shutdown of the JVM. Use http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/shutdown-agents[shutdown-agents] to terminate these threads and allow shutdown.

== Example

This example is an implementation of the send-a-message-around-a-ring test. A chain of n agents is created, then a sequence of m actions are dispatched to the head of the chain and relayed through it.
[source,clojure]
----
(defn relay [x i]
  (when (:next x)
    (send (:next x) relay i))
  (when (and (zero? i) (:report-queue x))
    (.put (:report-queue x) i))
  x)

(defn run [m n]
  (let [q (new java.util.concurrent.SynchronousQueue)
        hd (reduce (fn [next _] (agent {:next next}))
                   (agent {:report-queue q}) (range (dec m)))]
    (doseq [i (reverse (range n))]
      (send hd relay i))
    (.take q)))

; 1 million message sends:
(time (run 1000 1000))
->"Elapsed time: 2959.254 msecs"
----

== Related functions

Create an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent[agent]

Examine an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/deref[deref] _(see also the +@+ <<reader#,reader>> macro)_ http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-handler[error-handler] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-mode[error-mode]

Change Agent state: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send[send] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/send-off[send-off] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent]

Block waiting for an Agent: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/await[await] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/await-for[await-for]

Ref validators: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-validator![set-validator!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get-validator[get-validator]

Watchers: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/add-watch[add-watch] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/remove-watch[remove-watch]

Agent thread management: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/shutdown-agents[shutdown-agents]

Agent error management: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/agent-error[agent-error] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/restart-agent[restart-agent] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-error-handler![set-error-handler!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-handler[error-handler] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-error-mode![set-error-mode!] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/error-mode[error-mode]
