= Атомы
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:prevpagehref: agents
:prevpagetitle: Agents
:nextpagehref: reducers
:nextpagetitle: Reducers

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Атомы позволяют управлять общими, синхронными, независимыми состояниями. Они являются ссылочными типами как ссылки и переменные. Вы создаете атом с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/atom[atom] и можете осуществлять доступ к его состоянию с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/deref[deref/@]. Как ссылки и агенты, атомы поддерживают валидаторы. Чтобы изменить значение атома, вы можете использовать http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/swap![swap!]. Также предоставляется низкоуровневая функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/compare-and-set![compare-and-set!]. Изменения в атомах всегда защищены от https://ru.wikipedia.org/wiki/Состояние_гонки[состояния гонки].

As with all reference types, the intended use of atom is to hold one of Clojure's immutable data structures. And, similar to ref's alter and agent's send, you change the value by applying a function to the old value. This is done in an atomic manner by http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/swap![swap!] Internally, http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/swap![swap!] reads the current value, applies the function to it, and attempts to compare-and-set it in. Since another thread may have changed the value in the intervening time, it may have to retry, and does so in a spin loop. The net effect is that the value will always be the result of the application of the supplied function to a current value, atomically. However, because the function might be called multiple times, it must be free of side effects.

Atoms are an efficient way to represent some state that will never need to be coordinated with any other, and for which you wish to make synchronous changes (unlike agents, which are similarly independent but asynchronous). A typical usage might be for memoization:

[source,clojure]
----
(defn memoize [f]
  (let [mem (atom {})]
    (fn [& args]
      (if-let [e (find @mem args)]
        (val e)
        (let [ret (apply f args)]
          (swap! mem assoc args ret)
          ret)))))

(defn fib [n]
  (if (<= n 1)
    n
    (+ (fib (dec n)) (fib (- n 2)))))

(time (fib 35))
user=> "Elapsed time: 941.445 msecs"

(def fib (memoize fib))

(time (fib 35))

user=> "Elapsed time: 0.044 msecs"
----
