= Структуры данных
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:toclevels: 1
:icons: font
:prevpagehref: other_functions
:prevpagetitle: Other Functions
:nextpagehref: datatypes
:nextpagetitle: Datatypes

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Clojure имеет богатый набор структур данных, которые объединяют следующие свойства:

* Они неизменяемы
* Они предназначены для чтения
* Они правльно поддерживают метод equals
* Они предоставляют качественные hash-значения
* Также, коллекции:
** Управляются через интерфейсы.
** Поддерживают итерирование
** Поддерживают сохраняемые манипуляции.
** Поддерживают метаданные
** Реализуют java.lang.Iterable
** Реализуют обязательные методы (для чтения) класса java.util.Collection

[[nil]]
== nil

nil - это возможное значение любого типа данных в Clojure. nil имеет то же самое значение, что и null в Java. Система проверки условий Clojure основана на nil и false, которые представляют логическую ложь, когда любое другое значение представляет логическую истину. Также, nil используется как маркер конца последовательности в протоколе последовательностей.

[[Numbers]]
== Числа

Clojure по-умолчанию предоставляет полную поддержку значений-примитивов JVM, что позволяет реализовывать высокопроизводительный код для вычислительных приложений.

Также Clojure поддерживает классы-обертки Java, наследованные от java.lang.Number, включая BigInteger и BigDecimal, плюс свой собственный класс Ratio. Существуют следующие особенности:

=== Long

По-умолчанию Clojure оперирует натуральными числами как экземплярами примитивного типа long. Когда примитивные операции возвращают значение, которое не вмещается в long генерируется java.lang.ArithmeticException. Clojure предоставляет множество альтернативных операторов, заканчивающися апострофом: +', -', *', inc', и dec'. Эти операторы автоматически преобразуют число в BigInt при переполнении, но работают медленнее, чем обычные операторы.

=== Ratio

Представляет отношение между целыми числами. Результат деления целых чисел, который сам не является целым числом порождает дробь, т.е. 22/7 = 22/7, а не число с плавающей точкой и не число, обрезанное до целого.

=== Заражение

Объекты BigInt и типы чисел с плавающей точкой "заражают драгих" при операциях. Например, любые целочисленные операции, включающие BigInt будут в результате давать BigInt, а любые операции включающие double или float будут в результате давать double.

=== Литералы BigInt и BigDecimal

Целочисленные литералы для BigInt и BigDecimal определяются при помощи суффиксов N и M соответственно.

[cols="<*,", options="header", role="table"]
|===
| Выражение | Возвращаемое значение
| `(== 1 1.0 1M)` | `true`
| `(/ 2 3)` | `2/3`
| `(/ 2.0 3)` | `0.6666666666666666`
| `(map #(Math/abs %) (range -3 3))` | `(3 2 1 0 1 2)`
| `(class 36786883868216818816N)` | `clojure.lang.BigInt`
| `(class 3.14159265358M)` | `clojure.lang.BigDecimal`
|===

=== Функции

[%hardbreaks]
Вычисление: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2B[\+] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2D[-] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2A[\*]  http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2F[/]  http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/inc[inc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dec[dec]  http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/quot[quot] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/rem[rem] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/min[min] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/max[max]
Автоматически расширяющие вычисления: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2B%27[+'] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2D%27[-'] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2A%27[*'] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/inc%27[inc'] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dec%27[dec']
Сравнение: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%3D%3D[==] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%3C[<] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%3C%3D[<=] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%3E[>] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%3E%3D[>=] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/zero%3F[zero?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pos%3F[pos?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/neg%3F[neg?]
Битовые операции: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-and[bit-and] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-or[bit-or] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-xor[bit-xor] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-not[bit-not] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-shift-right[bit-shift-right] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bit-shift-left[bit-shift-left]
Соотношения: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/numerator[numerator] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/denominator[denominator]
Приведение: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/int[int] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bigdec[bigdec] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/bigint[bigint] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/double[double] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/float[float] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/long[long] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/num[num] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/short[short]

[[Strings]]
== Строки

Строки в Clojure являются объектами-строками Java. См. также <<other_functions#printing#,Печать>>.
[source,clojure-repl]
----
user=> (map (fn [x] (.toUpperCase x)) (.split "Dasher Dancer Prancer" " "))
("DASHER" "DANCER" "PRANCER")
----

=== Функции

http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/str[str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/string?[string?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr-str[pr-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn-str[prn-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/print-str[print-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/println-str[println-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-out-str[with-out-str]

[[Characters]]
== Символы
Символы в Clojure такие же как в Java.

=== Функции
http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/char[char] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/char-name-string[char-name-string] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/char-escape-string[char-escape-string]

[[Keywords]]
== Ключевые слова
Ключевые слова - символические идентификаторы, которые разрешаются сами в себя. Они позволяют значительно быстрее производить проверку на равенство. Как символы, они имеют имена и необязательное <<namespaces#,пространство имен>>, оба из которых являются строками. Начальный ':' не является частью пространства имен или имени.

Ключевые слова реализуют интерфейс IFn, чтобы вызывать invoke() с одним аргументом (ассоциативным массивом) и необязательным вторым аргументом (значение по-умолчанию). Например `(:mykey my-hash-map :none)` означает тоже самое, что `(get my-hash-map :mykey :none)`. См. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get[get].

=== Функции
http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/keyword[keyword] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/keyword?[keyword?]
[[Symbols]]

== Символы
Символы - это идентификаторы, которые обычно используются, чтобы на что-то ссылаться. Они моугт быть использованы в формах программы, чтобы ссылаться на параметры функции, устанавливать связи, имена классов и глобальные переменные. У них есть имена и необязательное <<namespaces#,пространство имён>>, оба - строки. Символы могут иметь метаданные (см. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-meta[with-meta]).

Символы, как и ключевые слова, реализуют интерфейс IFn, чтобы вызывать invoke() с одним аргументом(ассоциативным массивом) и необязательным вторым аргументом (значение по-умолчанию). Например `('mysym my-hash-map :none)` означает то же самое что `(get my-hash-map 'mysym :none)`. См. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get[get].

=== Функции
http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/symbol[symbol] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/symbol?[symbol?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/genysm[gensym] (см. также макрос <<reader#,считывателя>> с суффиксом \#)

[[Collections]]
== Коллекции

Все коллекции Clojure являются неизменяемыми и https://en.wikipedia.org/wiki/Persistent_data_structure[стойкие]. В частности, коллекции Clojure поддерживают эффективное создание 'модифицированных' версий, с использованием структурного обмена. Коллекции эффективны и потоконезависимы. Коллекции представлены в виде абстракций, и у них может быть одна или несколько конекретных реализаций. В частности, так как операции 'модификации' порождают новую коллекцию, эта новая коллекция может не иметь тот же самый тип, что исходная, но будет реализовывать тот же логический тип (интерфейс).

Все коллекции поддерживают http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/count[count] чтобы узнать размер коллекции, http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/conj[conj] для 'добавления' элементов и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/seq[seq] чтобы получать последовательность, которая поможет пройти по всей коллекции, хотя их конкретное поведение немного отличается для различных типов коллекций.

Так как коллекции поддерживают функцию http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/seq[seq], все <<sequences#,функции обработки последовательностей>> могут быть использованы с любой коллекцией.

[[hash]]
=== Хеш-суммы коллекций Java
Интерфейсы коллекций Java определяют алгоритмы вычисления hashCode() для классов http://docs.oracle.com/javase/7/docs/api/java/util/List.html#hashCode()[List], http://docs.oracle.com/javase/7/docs/api/java/util/Set.html#hashCode()[Set], and http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#hashCode()[Map]. Все алгоритмы вычисления hashCode() коллекций Clojure соответствуют этим определениям.

=== Хеш-суммы коллекций Clojure
Clojure предоставляет свой алгоритм вычисления хеш-суммы, немного лучше работающий с коллекциями и другими типами, известный как _hasheq_.

Интерфейс `IHashEq` помечает коллекции, которые предоставляют функцию `hasheq()` - для вычисления значения hasheq. Также, в Clojure функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/hash[hash] может быть использована, чтобы вычислить значение hasheq.

Упорядоченные коллекции (векторы, списки, последовательности и т.д.) обязаны использовать следующий алгоритм для вычисления haseq (где hash вычисляет hasheq). Заметим, что unchecked-add-int и unchecked-multiply-int используются для выполнения операций над целыми числами с переполнением.
[source,clojure]
----
(defn hash-ordered [collection]
  (-> (reduce (fn [acc e] (unchecked-add-int
                            (unchecked-multiply-int 31 acc)
                            (hash e)))
              1
              collection)
      (mix-collection-hash (count collection))))
----
Неупорядоченные коллекции (ассоциативные массивы, множества) обязаны использовать следующий алгоритм для вычисления hasheq. Элемент ассоциативного массива рассматривается как упорядоченная коллекция, состоящая из ключа и значения. Заметим, что unchecked-add-int используется для выполнения операций над целыми числами с переполнением.
[source,clojure]
----
(defn hash-unordered [collection]
  (-> (reduce unchecked-add-int 0 (map hash collection))
      (mix-collection-hash (count collection))))
----
Алгоритм работы http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/mix-collection-hash[mix-collection-hash] - это деталь реализации и может изменяться.

[[Lists]]
== Списки (IPersistentList)

Списки являются коллекциями. Они реализуют интерфейс ISeq напрямую (кроме пустых списков, которые не являются корректной последовательностью). Функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/count[count] имеет сложность O(1). Функция http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/conj[conj] добавляет элементы в начало списка.

=== Функции

[%hardbreaks]
Создать список: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/list[list] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/list*[list*]
Работать со списком как со стеком: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/peek[peek] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pop[pop]
Проверить, является ли объект списком: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/list?[list?]

[[Vectors]]
== Вектора (IPersistentVector)

Вектор - это пронумерованная коллекция значений. Вектора поддерживают доступ к элементу по его номеру за log32N шагов. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/count[count] - за время O(1). http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/conj[conj] помещает элемент в конец вектора. Вектора также поддеживают http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/rseq[rseq], которая возвращает элементы в обратном порядке. Вектора реализуют IFn, для invoke() с одним аргументом, который рассматривается как номер. В качестве результата возвращается элемент, соответствующий этому номеру. Таким образом, вектора - это функции, переводящая номер в элемент. Вектора сначала сравниваются по длине, потом поочередно сравниваются элементы.

=== Функции

[%hardbreaks]
Создать вектор: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/vector[vector] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/vec[vec] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/vector-of[vector-of]
Проверить вектор: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get[get] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/nth[nth] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/peek[peek] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/rseq[rseq] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/vector?[vector?]
'Изменить' вектор: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/assoc[assoc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pop[pop] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/subvec[subvec] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/replace[replace]

Также смотри <<other_libraries#,zipper-ы>>

[[Maps]]
== Ассоциативный массив (IPersistentMap)

Ассоциативный массив - это коллекция, которая ставит в соответствие ключи и значения. Предоставляются два типа ассоциативных массивов - сортированные и хэшированные. Хэшированные массивы требуют, чтобы ключи поддерживали hashCode и equals. Сортированные массивы требуют, чтобы ключи реализовывали Comparable, или экземпляр класса Comparator. Хэшированные массивы предоставляют более быстрый доступ log32N шагов против logN шагов, но сортированные массивы зато отсортированы. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/count[count] - сложность O(1). http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/conj[conj] ожидает другой ассоциативный массив (возможно состоящий из одной записи), как аргумент, и возвращает новый массив, содержащий записи из старого и из нового, причем новые записи перезаписывают старые. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/conj[conj] также принимают MapEntry или вектор из двух элементов (ключ и значение). http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/seq[seq] возвращает последовательность записей массива, т.е. пары ключ-значение. Сортированные массивы также поддерживают http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/rseq[rseq], которая возвращает записи в обратном порядке. Ассоциативные массивы реализуют IFn, для invoke() с одним аргументом (ключем) с опциональным вторым аргументом (значение по-умолчанию), то есть ассоциативные массивы - это функции их ключей. Значечния ключей и значений nil разрешены.

=== Функции

[%hardbreaks]
Создать новый ассоциативный массив: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/hash-map[hash-map] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/sorted-map[sorted-map] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/sorted-map-by[sorted-map-by]
'Изменить' массив: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/assoc[assoc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dissoc[dissoc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/select-keys[select-keys] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/merge[merge] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/merge-with[merge-with] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/zipmap[zipmap]
Просмотреть ассоциативный массив: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get[get] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/contains?[contains?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/find[find] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/keys[keys] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/vals[vals] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/map?[map?]
Просмотреть элемент массива: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/key[key] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/val[val]

[[StructMaps]]
== StructMap-ы

[ВНИМАНИЕ]
В большинстве случаев, вместо использования StructMap лучше использовать <<datatypes#,records>>.

Часто несколько экземпляров ассоциативных массивов имеют один и тот же набор ключей, например когда они используются также, как струкутры или объекты в других языках программирования. StructMap поддерживают этот вариант использования, эффективно переиспользуя информацию о ключах, а также предоставляя опциональные методы доступа к этим ключам с повышенной производительностью. StructMap во всех отношениях являются ассоциативными массивами, поддерживающими тот же набор функций, совместимыми с другими ассоциативными массивами, и являются расширяемыми (т.е. они не ограничены своими базовыми ключами). Единственное ограничение - вы не можете отделить StructMap от одного из его базовых ключей. StructMap будет по прежнему хранить свои базовые ключи.

Чтобы создать StructMap нужно сначала создать базовый объект структуры с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/create-struct[create-struct] или http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defstruct[defstruct], затем создать экземпляры с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/struct-map[struct-map] или http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/struct[struct].

[source,clojure]
----
(defstruct desilu :fred :ricky)
(def x (map (fn [n]
              (struct-map desilu
                :fred n
                :ricky 2
                :lucy 3
                :ethel 4))
             (range 100000)))
(def fred (accessor desilu :fred))
(reduce (fn [n y] (+ n (:fred y))) 0 x)
 -> 4999950000
(reduce (fn [n y] (+ n (fred y))) 0 x)
 -> 4999950000
----

=== Функции

[%hardbreaks]
Объявление StructMap: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/create-struct[create-struct] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defstruct[defstruct] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/accessor[accessor]
Создать отдельную структуру: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/struct-map[struct-map] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/struct[struct]

[[ArrayMaps]]
== ArrayMaps

When doing code form manipulation it is often desirable to have a map which maintains key order. An array map is such a map - it is simply implemented as an array of key val key val... As such, it has linear lookup performance, and is only suitable for _very small_ maps. It implements the full map interface. New ArrayMaps can be created with the http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/array-map[array-map] function. Note that an array map will only maintain sort order when un-'modified'. Subsequent assoc-ing will eventually cause it to 'become' a hash-map.

[[Sets]]
== Sets
Sets are collections of unique values.

There is literal support for hash-sets:

[source,clojure]
----
#{:a :b :c :d}
-> #{:d :a :b :c}
----

You can create sets with the http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/hash-set[hash-set] and http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/sorted-set[sorted-set] functions:

[source,clojure]
----
(hash-set :a :b :c :d)
-> #{:d :a :b :c}

(sorted-set :a :b :c :d)
-> #{:a :b :c :d}
----

You can also get a set of the values in a collection using the http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set[set] function:

[source,clojure]
----
(set [1 2 3 2 1 2 3])
-> #{1 2 3}
----

Sets are collections:
[source,clojure]
----
(def s #{:a :b :c :d})
(conj s :e)
-> #{:d :a :b :e :c}

(count s)
-> 4

(seq s)
-> (:d :a :b :c)

(= (conj s :e) #{:a :b :c :d :e})
-> true
----

Sets support 'removal' with http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/disj[disj], as well as _**contains?**_ and _**get**_, the latter returning the object that is held in the set which compares equal to the key, if found:

[source,clojure]
----
(disj s :d)
-> #{:a :b :c}

(contains? s :b)
-> true

(get s :a)
-> :a
----

Sets are functions of their members, using _**get**_:
[source,clojure]
----
(s :b)
-> :b

(s :k)
-> nil
----

Clojure provides basic set operations like http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/union[union] / http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/difference[difference] / http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/intersection[intersection], as well as some pseudo-relational algebra support for 'relations', which are simply sets of maps - http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/select[select] / http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/index[index] / http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/rename[rename] / http://clojure.github.io/clojure/clojure.set-api.html#clojure.set/join[join].
