= Отличия от других диалектов Lisp
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:navlinktext: Differences with Lisps
:prevpagehref: other_libraries
:prevpagetitle: Other Libraries

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Эта информация предоставлена для программистов, знакомых с Common List или Scheme.

* Clojure чувствителен к регистру
* Clojure это Lisp-1
* () не то же самое что nil
* Считыватель не имеет побочных действий
* Ключевые слова - это не знаки
* Знаки - это не хранилища (см. раздел о переменных)
* _**nil**_ это не знак
* t не принадлежит синтаксису, используйте _**true**_
* Таблица чтения сейчас недоступна для пользовательских программ
* _**let**_ присваивает последоательно
* _**do**_ не циклическая конструкция
* Не существует хвостовой рекурсии, используйте _**recur**_.
* кавычка разрешает знак в текущем контекте, то есть `x не то же самое что 'x.
* ` автоматически создает структуры данных.
* ~ отменяет знак цитирования `, а ',' - это пробельный символ
* Существует синтаксис считывателя для ассоциативных массивов, векторов и множеств
* _**cons**_, _**first**_ и _**rest**_ регулируют абстракцию последовательности, не конкретные ячейки cons
* Большинство структур данных неизменяемы
* лямбда - это _**fn**_, и поддерживает перегрузку по количеству параметров
* _**pass:[=]**_ - это предикат эквивалентности
* Глобальные переменные могут быть динемически переопределены (если объявлены динамически) без лексических локальных определений переменных. Для различения динамических и лексических привязок не требуется специальных деклараций. Так как Clojure - это Lisp-1, глобальные функции могут быть динемически переопределены (если они отмечены как динамические).
* Нет letrec, labels или flet - используйте (fn name [args]...) для анонимных функций, http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/letfn[letfn] для взаимных ссылок.
* В Clojure _**nil**_ означает 'ничего'. Это обозначает отсутствие значения любого типа и не относится к спискам и последовательностям.
* Пустые коллекции отличаются от _**nil**_. Clojure не приравнивает _**nil**_ и '().
* _**false**_ означает одно из двух возможных значений типа boolean, другой из которых - _**true**_
* There is more to collections than lists. You can have instances of empty collections, some of which have literal support ([], {}, and ()). Thus there can be no sentinel empty collection value.
* Coming from Scheme, _**nil**_ may map most closely to your notion of #f.
* A big difference in Clojure, is sequences. Sequences are not specific collections, esp. they are not necessarily concrete lists. When you ask an empty collection for a sequence of its elements (by calling *seq*) it returns _**nil**_, saying "I can't produce one". When you ask a sequence on its last element for the _**rest**_ it returns _**another logical sequence.**_ You can only tell if that sequence is empty by calling *seq* on it in turn. This enables sequences and the sequence protocol to be _lazy_.
* Some of the sequence functions correspond to functions from Scheme and CL that there manipulated only pairs/conses ('lists') and returned sentinel values ('() and nil) that represented 'empty' lists. The Clojure return values differ in not returning specific empty collections, but rather another logical sequence. Some of the sequence functions have no counterpart in Scheme/CL, and map to Haskell/ML-like functions. Some of those functions return infinite or calculated sequences, where the analogy to concrete data-structures like Scheme/CL lists is tenuous at best.
* It helps to distinguish collections/data-structures and seqs/iteration. In both CL and Scheme they are conflated, in Clojure they are separate.

[cols="<*,", options="header", role="table"]
|===
|   | Clojure | Common Lisp | Scheme | Java |
| Has nil? | nil - means 'nothing' | nil - means false or empty list | - | null |
| Has true? | true | - | #t | true (primitive) |
| Has false? | false | - | #f | false (primitive) |
| Conditionals distinguish: | nil or false/ everything else | nil/non-nil | #f/non-#f | false/true |
| List/sequence library manipulates distinguished concrete type(s)? | No - seq abstraction with many collection implementations | Yes - cons and vector | Yes - pair | No - Iterator abstraction with many collection implementations |
| Singleton empty-list value? | No - can have distinct empty values of concrete collection types | nil | '() | No |
| End-of-sequence returns: | a logical sequence for which *seq* returns nil | nil | '() | false |
| Host null: | nil | NA | NA | NA |
| Host true: | true (boxed) | NA | NA | NA |
| Host false: | false (boxed) | NA | NA | NA |
|===
