= Макросы
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:prevpagehref: special_forms
:prevpagetitle: Special Forms
:nextpagehref: other_functions
:nextpagetitle: Other Functions

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

У Clojure есть программная система макросов, которая позволяется компилятору расширять пользовательский код. Макросы могут быть использованы для определения синтаксических конструкций, которые требовали бы примитивов или втроенной поддержки в других языках программирования. Многие ключевые конструкции в Clojure на самом деле являются не примитивами, а макросами.

Некоторые макросы производят простые комбинации форм-примитивов. Например, http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/when[`when`] соединяет <<special_forms#if#,`if`>> и <<special_forms#do#,`do`>>:

[source,clojure-repl]
----
user=> (macroexpand '(when (pos? a) (println "positive") (/ b a)))
(if (pos? a) (do (println "positive") (/ b a)))
----

Другие макросы переставляют формы в удобном порядке, например макрос `pass:[->]`, который рекурсивно вставляет каждое выражение как первый аргумент следующего выражения.

[source,clojure-repl]
----
user=> (-> {} (assoc :a 1) (assoc :b 2))
{:b 2, :a 1}
user=> (macroexpand '(-> {} (assoc :a 1) (assoc :b 2)))
(assoc (clojure.core/-> {} (assoc :a 1)) :b 2)
----

== Специальные переменные

Для удобства внутри defmacro доступно две специальные переменные:

* `&form` - исходная исполняемая форма (в виде данных)
* `&env` - соответствие локальных привязок в точке вызова макроса. Это соответствие символов и объектов содержащее информацию компилятора о этой связи.

Все следующие макросы описаны на странице http://clojure.github.io/clojure/[API]. Многие уже были упомянуты на указанных страницах:

[%hardbreaks]
Макросы создания: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmacro[defmacro] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/definline[definline] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/macroexpand-1[macroexpand-1] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/macroexpand[macroexpand]
Ветвление: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/and[and] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/or[or] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/when[when] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/when-not[when-not] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/when-let[when-let] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/when-first[when-first] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/if-not[if-not] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/if-let[if-let] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/cond[cond] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/condp[condp]
Циклы (см. также <<sequences#,Последовательности>>): http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/for[for] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/doseq[doseq] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dotimes[dotimes] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/while[while]
Работа с переменнымт (см. также <<vars#,Переменные и глобальное окружение>>): http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/declare[declare] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defn[defn] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmacro[defmacro] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/definline[definline] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmethod[defmethod] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmulti[defmulti] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defn-[defn-] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defonce[defonce] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defstruct[defstruct]
Различные преобразования кода: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2E%2E[..] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/doto[doto] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/-%3e[pass:[->]]
Динамические переменные (см. также <<vars#,Переменные и глобальное окружение>>): http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/binding[binding] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/locking[locking] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/time[time] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-in-str[with-in-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-local-vars[with-local-vars] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-open[with-open] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-out-str[with-out-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-precision[with-precision]
Создание ленивых объектов (см. также <<sequences#,Последовательности>>): http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/lazy-cat[lazy-cat] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/lazy-cons[lazy-cons] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/delay[delay]
Макросы <<java_interop#,Взаимодействие с Java>>: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/%2E%2E[..] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/amap[amap] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/areduce[areduce] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/gen-class[gen-class] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/gen-interface[gen-interface] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/proxy[proxy] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/proxy-super[proxy-super] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/memfn[memfn]
Документирование кода: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/assert[assert] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/comment[comment] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/doc[doc]
Транзакции: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dosync[dosync] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/io![io!]

Несколько <<special_forms#,специальных форм>> на самом деле реализованы как макросы, прежде всего подерживающие реструктуризирующее присваивание: fn let loop
