= Метаданные
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:prevpagehref: protocols
:prevpagetitle: Protocols
:nextpagehref: namespaces
:nextpagetitle: Namespaces

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Знаки и коллекции поддерживают метаданные - ассоциативные массивы данных _про_ знак или коллекцию. Система метаданных позволяет произвольно аннотировать данные. Это используется для передачи информации о типах компилятору, но также может быть использовано разработчиками для различных целях: аннотирования источников данных, соглашений и прочее.

Важно понять о метаданных, что они не рассматриваются как часть значения объекта. Как таковые, _метаданные не влияют на эквивалентность (или хэш-код)_. Два объекта, различающиеся только метаданными являются эквивалентными.

Тем не менее, метаданные и их отношения с объектами неизменны: объект с другими метаданными - это уже другой объект. Следовательно добавление метаданных к ленивой последовательности будет вычислять первый элемент, чтобы оба объекта могли переиспользовать одну последовательность.

''''

== (_meta_ obj)

Возвращает метаданные obj или nil если их нет.

''''

== (_with-meta_ obj map)
Возвращает объект с тим же типом и значением, что и obj, с map в качестве метаданных.

== Макрос считывателя

В дополнении к with-meta существует несколько макросов считывателя (<<reader#macrochars,Считыватель: Макросимволы>>)
 для добавления метаданных к выражению:

* `^{:doc "How obj works!"} obj` - Устанавливает предоставленный ассоциативный массив как метаданные obj.
** То же что и `(with-meta obj {:doc "How obj works!"})`
* `^:dynamic obj` - Устанавливает заданное ключевое слово, соответствующее true как метаданные объекта.
** То же что `^{:dynamic true} obj`
* `^String obj` - Устанавливает значение ключа :tag в метаданных объекта.
** То же что `^{:tag java.lang.String} obj`
** Используется чтобы подсказать тип объекта компилятору Clojure. Раздел <<java_interop#typehints,Интеграция с Java: Подсказки типов>> содержит более детальную информацию и полный список специальных подсказок о типах.

Возможно добавлять несколько пар значений метаданных, если группировать макросы вместе.
Например, `^:dynamic ^ints obj` добавит к объекту и флаг :dynamic, и подсказку о типе int.
