= Метаданные
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:prevpagehref: protocols
:prevpagetitle: Protocols
:nextpagehref: namespaces
:nextpagetitle: Namespaces

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Знаки и коллекции поддерживают метаданные - ассоциативные массивы данных _про_ знак или коллекцию. Система метаданных позволяет произвольно аннотировать данные. Это используется для передачи информации о типах компилятору, но также может быть использовано разработчиками для различных целях: аннотирования источников данных, соглашений и прочее.

Важно понять о метаданных, что они не рассматриваются как часть значения объекта. Как таковые, _метаданные не влияют на эквивалентность (или хэш-код)_. Два объекта, различающиеся только метаданными являются эквивалентными.

Тем не менее, метаданные и их отношения с объектами неизменны: объект с другими метаданными - это уже другой объект. Следовательно добавление метаданных к ленивой последовательности будет вычислять первый элемент, чтобы оба объекта могли переиспользовать одну последовательность.

''''

== (_meta_ obj)

Возвращает метаданные obj или nil если их нет.

''''

== (_with-meta_ obj map)
Returns an object of the same type and value as obj, with map as its metadata.

== Metadata Reader Macros

In addition to with-meta, there are a number of reader macros (<<reader#macrochars,The Reader: Macro Characters>>) for applying metadata to the expression following it:

* `^{:doc "How obj works!"} obj` - Sets the metadata of obj to the provided map.
** Equivalent to `(with-meta obj {:doc "How obj works!"})`
* `^:dynamic obj` - Sets the given keyword to true in the object's metadata.
** Equivalent to `^{:dynamic true} obj`
* `^String obj` - Sets the value of :tag key in the object's metadata.
** Equivalent to `^{:tag java.lang.String} obj`
** Used to hint an objects type to the Clojure compiler. See <<java_interop#typehints,Java Interop: Type Hints>> for more information and a complete list of special type hints.

It is possible to add multiple pieces of metadata by chaining the metadata reader macros together.
For example: `^:dynamic ^ints obj` would apply both the :dynamic flag and ints type-hint to obj.
