= Пространства имен
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:icons: font
:prevpagehref: metadata
:prevpagetitle: Metadata
:nextpagehref: libs
:nextpagetitle: Libs

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Пространства имен - это соответствие между простыми (неуточненными) знаками и переменными/классами.Переменные могут быть добавлены в пространство имен с помощью _**def**_, а также с помощью любого из вариантов функции _**def**_. В этом случае у переменной появится некоторый знак в качестве имени, а также ссылка на пространство имен, в которое добавится соответствие между этим знаком и переменной.Также пространство имен может заимствовать пары знак-переменная из других пространств имен с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/refer[refer], http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/use[use] или пары знак-класс с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/import[import]. Заметим, что пространства имен являются https://ru.wikipedia.org/wiki/Объект_первого_класса[объектами первого класса]. Они могут динамически создаваться, удаляться и модифицироваться во время исполнения и в REPL.

Лучший способ создать новое пространство имен в начале файла Clojure - использовать http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[макрос ns]. По-умолчанию он создаст новое пространство имен, содержащее пары-соответствия для имен классов из +java.lang+, `clojure.lang.Compiler` а также функций `clojure.core`.

В REPL лучше всего использовать http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns], которая для нового пространства имен добавляет только соответствия для имен классов из +java.lang+. Чтобы получить доступ к именам из пространства имен `clojure.core`, вам нужно будет выполнить +(clojure.core/refer 'clojure.core)+. Для пространства имен `user` в REPL это уже сделано за вас.

Текущее пространство имен _pass:[*ns*]_ может и должно устанавливаться только с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns] или http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[макроса ns]. В обоих случаях пространство имен будет создано, если таковое не существует.

== Функции

[%hardbreaks]
Создание и переключение в пространство имен: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/create-ns[create-ns]
Добавление в пространство имен: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/alias[alias] <<special_forms#def#,def>> http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/import[import] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/intern[intern] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/refer[refer]
Проверка, что пространство имен существует: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/all-ns[all-ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/find-ns[find-ns]
Просмотр пространства имен: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-name[ns-name] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-aliases[ns-aliases] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-imports[ns-imports] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-interns[ns-interns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-map[ns-map] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-publics[ns-publics] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-refers[ns-refers]
Получение переменных/классов, соответсвующих знаку в пространстве имен: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/resolve[resolve] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-resolve[ns-resolve] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/namespace[namespace]
Удаление соответствий: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-unalias[ns-unalias] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-unmap[ns-unmap] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/remove-ns[remove-ns]
