= Пространства имен
Rich Hickey
2015-01-01
:jbake-type: page
:toc: macro
:toc-title: Содержание

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Пространства имен

Пространства имен - это соответствие между простыми (неуточненными) знаками и переменными/классами. Переменные могут быть добавлены в пространство имен с помощью _**def**_, а также с помощью любого из вариантов _**def**_. В этом случае у переменной появится некоторый знак в качестве имени, а пространство имен будет содержать соответствие между этим знаком и переменной. Также пространство имен может заимствовать пары знак-переменная из других пространств имен с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/refer[refer], http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/use[use] или пары знак-класс с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/import[import]. Заметим, что пространства имен являются https://ru.wikipedia.org/wiki/Объект_первого_класса[объектами первого класса]. Они могут динамически создаваться, удаляться и модифицироваться во время исполнения и в REPL.

The best way to set up a new namespace at the top of a Clojure source file is to use the http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[ns macro]. By default this will create a new namespace contains mappings for the classnames in +java.lang+ plus `clojure.lang.Compiler`, and the functions in `clojure.core`.

At the Repl it's best to use http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns], in which case the new namespace will contain mappings only for the classnames in +java.lang+. In order to access the names from the `clojure.core` namespace you must execute +(clojure.core/refer 'clojure.core)+. The `user` namespace at the Repl has already done this.

The current namespace, _pass:[*ns*]_ can and should be set only with a call to http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns] or the http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[ns macro], both of which create the namespace if it doesn't exist.

=== Related functions 

[%hardbreaks]
Creating and switching to a namespace: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/in-ns[in-ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns[ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/create-ns[create-ns]
Adding to a namespace: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/alias[alias] <<special_forms#def#,def>> http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/import[import] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/intern[intern] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/refer[refer]
Finding what namespaces exist: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/all-ns[all-ns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/find-ns[find-ns]
Examining a namespace: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-name[ns-name] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-aliases[ns-aliases] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-imports[ns-imports] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-interns[ns-interns] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-map[ns-map] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-publics[ns-publics] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-refers[ns-refers]
Getting a namespace from a symbol: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/resolve[resolve] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-resolve[ns-resolve] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/namespace[namespace]
Removing things: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-unalias[ns-unalias] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/ns-unmap[ns-unmap] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/remove-ns[remove-ns]
