= Другие полезные функции и макросы
Rich Hickey
2015-01-01
:type: reference
:toc: macro
:toc-title: Содержание
:toclevels: 1
:icons: font
:navlinktext: Other Functions
:prevpagehref: macros
:prevpagetitle: Macros
:nextpagehref: data_structures
:nextpagetitle: Data Structures

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

[%hardbreaks]
Булевы функции и функции проверки: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/=[=] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/==[==] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/identical?[identical?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/not=[not=] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/not[not] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/true?[true?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/false?[false?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/nil?[nil?]
Разное: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/identity[identity] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/dotimes[dotimes] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/time[time] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/assert[assert] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-open[with-open]

[[creating-functions]]
== Функции создания

[cols="<*,", options="header", role="table"]
|===
| Функция | Пример выражения | Возвращаемое значение |
| <<special_forms#fn#,fn>> | `(map (fn [x] (+ 2 x)) [1 2 3])` | `(3 4 5)` |
| pass:[#()] <<reader#,reader>> macro | `(map #(+ 2 %) [1 2 3])` | `(3 4 5)` |
| http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/partial[partial] | `(map (partial + 2) [1 2 3])` | `(3 4 5)` |
| http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/comp[comp] | `(map (comp - *) [2 4 6] [1 2 3])` | `(-2 -8 -18)` |
| http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/complement[complement] | `(map (complement zero?) [3 2 1 0])` | `(true true true false)` |
| http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/constantly[constantly] | `(map (constantly 9) [1 2 3])` | `(9 9 9)` |
|===

[[printing]]
== Печать

Существуют несколько функций, чтобы печатать объекты в поток вывода - текущее значение *out*. Версии с суффиксом -str привязывают *out* к StringWriter, печатают в него и возвращают полученную строку. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr[pr] печатает объект(ы), разделенные пробелами, если их более одного. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn[prn] делает то же самое и в конце печатает символ новой строки http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/newline[newline]. http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/print[print] и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/println[println] вызывают http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr[pr] и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn[prn] соответственно, c `pass:[*print-readably*]` (которая по-умолчанию равен true) привязанной к nil, из-за чего строки печатаются без кавычек и без экранирования, а символы без начального '\' и также без экранирования. По-умолчанию, http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr[pr] и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn[prn] печатают объекты так, чтобы они могли быть прочитаны считавателем, а http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/print[print] и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/println[println] выводят объекты в удобном для чтения человеком виде. Когда `pass:[*print-readably*]` не nil, вывод метаданных регулируется `pass:[*print-meta*]`, который равен nil по-умолчанию.

=== Функции

[%hardbreaks]
Печать в pass:[*out*]: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr[pr] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn[prn] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/print[print] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/println[println] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/newline[newline]
Печать в строку: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/pr-str[pr-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/prn-str[prn-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/print-str[print-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/println-str[println-str] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-out-str[with-out-str]

[[regex]]
== Поддержка регулярных выражений

Регулярные выражения могут быть скомпилированы во время чтения с помощью макроса считывателя `#"pattern"` или во время исполнения с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-pattern[re-pattern]. Обе формы производят объекты класса http://java.sun.com/j2se/1.5.0/docs/api/java/util/regex/Pattern.html[java.util.regex.Pattern].

[source,clojure-repl]
----
user=> (re-seq #"[0-9]+" "abs123def345ghi567")
("123" "345" "567")
user=> (re-find #"([-+]?[0-9]+)/([0-9]+)" "22/7")
["22/7" "22" "7"]
user=> (let [[a b c] (re-matches #"([-+]?[0-9]+)/([0-9]+)" "22/7")]
         [a b c])
["22/7" "22" "7"]
user=> (re-seq #"(?i)[fq].." "foo bar BAZ QUX quux")
("foo" "QUX" "quu")
----

=== Функции
http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-matcher[re-matcher] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-find[re-find] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-matches[re-matches] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-groups[re-groups] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/re-seq[re-seq]
