= Переменные
Rich Hickey
2015-01-01
:jbake-type: page
:toc: macro
:toc-title: Содержание

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Переменные и глобальное окружение

Clojure - прикладной язык программирования, который признает необходимость время от времени держать постоянные ссылки на изменяемые значения и предлагает для этого 4 различных механизма - переменные, <<refs#,ссылки>>, <<agents#,агенты>> и <<atoms#,атомы>>. Переменные позволяют ссылаться на изменяемое хранилище, которое может быть динамически заменено (на новое хранилище) для отдельного потока. Каждая переменная может (но не должна) иметь некоторую "главную" связь, которая будет использоваться потоками, не имеющими своей отдельной связи для данной переменной. Таким образом, значение переменной - это значение в хранилище, с которым связана эта переменная в текущем потоке, либо значение в главном хранилище.

Специальная форма _**def**_ осуществляет <<vars#interning,ленивое создание>> переменной. Если эта переменная не существовала и не было предоставлено начального значения - она будет несвязанной:

[source,clojure]
----
user=> (def x)
.'user/x
user=> x
java.lang.IllegalStateException: Var user/x is unbound.
----

Если начальное значение предоставлено - оно помещается в главное хранилище, связанное с переменной (даже если с переменная уже была связанна с некоторым хранилищем).

[source,clojure]
----
user=> (def x 1)
.'user/x

user=> x
1
----

По-умолчанию переменные являются статическими, но они могут быть помечены как динамические чтобы разрешить переопределение связанного хранилища для отдельного потока. Это осуществляется с помощью макроса http://clojure.github.com/clojure/clojure.core-api.html#clojure.core/binding[binding]. Внутри каждого потока динамические переменные подчиняются правилам стека:

[source,clojure]
----
user=> (def ^:dynamic x 1)
user=> (def ^:dynamic y 1)
user=> (+ x y)
2

user=> (binding [x 2 y 3]
         (+ x y))
5

user=> (+ x y)
2
----

Связи, созданные с помощью _**binding**_ не будут видны другим потокам. Также эти связи могут быть переопределены, что позволяет вложенным контекстам общаться с кодом, находящимся выше в стеке вызовов. Эта возможность доступна только после того, как для переменной установлен мета-тег _**dynamic**_, как в примере выше. Если необходимо переопределить статические переменные в некотором контексте - для этого Clojure (начиная с версии 1.3) предоставляет функции http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-redefs[with-redefs] и http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-redefs-fn[with-redefs-fn].

Функции определенные с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defn[defn] хранятся в переменных, что позволяет переопределять функции при исполнении программы. Также это позволяет применять подходы аспектно-ориентированного и контекстно-ориентированного программирования. Например, вы можете добавить в функцию журналирование только для некоторых контекстов или потоков.

[[set]]
=== (*set!* var-symbol expr)

Специальная форма присвоения.

Если в качестве первого операнда передан символ - ожидается, что он является глобальной переменной. Тогда в текущем потоке для этой переменной будет установлена связь со значением выражения expr. Попытка установить значение в главном хранилище переменной с помощью set! является ошибкой в текущей версии языка. В любом случае возвращается значение выражения expr.

Примечание - _вы не можете присвоить значение параметру функции или локальным связям. Только Java-поля, переменные, ссылки и агенты изменяемы в Clojure_.

Использование <<java_interop#set,set>> для Java-полей описано в <<java_interop#set,Java Interop>>.

[[interning]]
=== Ленивое создание
Система пространств имен поддерживает глобальные ассоциативные массивы, хранящие соответствие между знаками и переменными-объектами _(см. <<namespaces#,Пространства имен>>)_. Если выражение _**def**_ не находит запись, соответствующую определяемому знаку в текущем пространстве имен, оно создает такую запись. В противном случае _**def**_ использует существующую переменную-объект. Этот процесс поиска-создания называется ленивым созданием переменной. Это означает, что переменные-объекты являются неизменяемыми ссылками, пока не удалены из пространства имен. Это также означает, что пространства имен составляют глобальное окружение, в котором компилятор пытается разрешить все свободные знаки как переменные (см. <<evaluation#,Вычисление>>).

Специальная форма <<special_forms#var,var>> или маркос считывателя `pass:[#']` _(см. <<reader#,Считыватель>>)_ могут быть использованы, чтобы получить переменную-объект, а не её значение.

[[local-vars]]
=== Локальные переменные

Можно создавать переменные, которые не будут сохранены в глобальном окружении с помощью http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-local-vars[with-local-vars]. Такие переменные не будут автоматически обрабатываться при разрешении свободных знаков и их значения необходимо будет получать вручную. Тем не менее локальные переменные могут быть использованы как изменяемые ячейки-храниища, принадлежащие отдельному потоку.

[[related]]
=== Функции

[%hardbreaks]
Варианты _**def**_: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defn[defn] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defn-[defn-] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/definline[definline] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmacro[defmacro] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmethod[defmethod] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defmulti[defmulti] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defonce[defonce] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/defstruct[defstruct]
Работа с глобальными переменными: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/declare[declare] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/intern[intern] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/binding[binding] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/find-var[find-var] <<special_forms#var#,var>>
Работа с переменными-объеками: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-local-vars[with-local-vars] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/var-get[var-get] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/var-set[var-set] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/alter-var-root[alter-var-root] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/var?[var?] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-redefs[with-redefs] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/with-redefs-fn[with-redefs-fn]
Валидаторы переменных: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/set-validator[set-validator] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/get-validator[get-validator]
Общие метаданные переменных: http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/doc[doc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/find-doc[find-doc] http://clojure.github.io/clojure/clojure.core-api.html#clojure.core/test[test]
